name: valineups
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  bottom_navy_bar: ^6.0.0
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  font_awesome_flutter: ^10.7.0
  photo_view: ^0.15.0
  random_avatar: ^0.0.8
  random_name_generator: ^1.3.0
  shared_preferences: ^2.2.3
  lottie: ^3.0.0
  http: ^1.2.1
  shimmer: ^3.0.0
  flutter_swiper_view: ^1.1.8

  cloud_firestore: ^5.1.0
  google_sign_in: ^6.2.1
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  firebase_analytics: ^11.2.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

    - assets/images/loginScreen/

    - assets/images/onBoardingScreen/

    - assets/images/maps/

    - assets/images/agents/

    - assets/images/sides/

    - assets/images/mapsWiki/

    # Lineups BRIMSTONE

    # Lineups VIPER

    # Lineups OMEN

    # Lineups KILLJOY
    - assets/images/lineups/KILLJOY/BIND/
    - assets/images/lineups/KILLJOY/HAVEN/
    - assets/images/lineups/KILLJOY/SPLIT/
    - assets/images/lineups/KILLJOY/ASCENT/
    - assets/images/lineups/KILLJOY/ICEBOX/
    - assets/images/lineups/KILLJOY/BREEZE/
    - assets/images/lineups/KILLJOY/FRACTURE/
    - assets/images/lineups/KILLJOY/PEARL/
    - assets/images/lineups/KILLJOY/LOTUS/
    - assets/images/lineups/KILLJOY/SUNSET/
    - assets/images/lineups/KILLJOY/ABYSS/

    # Lineups CYPHER

    # Lineups SOVA

    # Lineups SAGE

    # Lineups PHOENIX

    # Lineups JETT

    # Lineups REYNA

    # Lineups RAZE

    # Lineups BREACH

    # Lineups SKYE

    # Lineups YORU

    # Lineups ASTRA

    # Lineups KAY/O

    # Lineups CHAMBER

    # Lineups NEON

    # Lineups FADE

    # Lineups HARBOR

    # Lineups GEKKO

    # Lineups DEADLOCK

    # Lineups ISO

    # Lineups CLOVE


  fonts:
    - family: valo-font
      fonts:
        - asset: assets/fonts/valo-font.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#131313"
  image: assets/splash/splash.png