name: valineups
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  bottom_navy_bar: ^6.0.0
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/splash.png
    - assets/images/maps/Bind.png
    - assets/images/maps/Haven.png
    - assets/images/maps/Split.png
    - assets/images/maps/Ascent.png
    - assets/images/maps/Icebox.png
    - assets/images/maps/Breeze.png
    - assets/images/maps/Fracture.png
    - assets/images/maps/Pearl.png
    - assets/images/maps/Lotus.png
    - assets/images/maps/Sunset.png
    - assets/images/maps/Abyss.png

  fonts:
    - family: valo-font
      fonts:
        - asset: assets/fonts/valo-font.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#131313"
  image: assets/splash.png