name: valineups
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  bottom_navy_bar: ^6.0.0
  firebase_analytics: ^11.1.0
  firebase_core: ^3.1.1
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  lottie: ^3.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

    - assets/images/loginScreen/anonimAuth.png
    - assets/images/loginScreen/googleAuth.png
    - assets/images/loginScreen/valoAgent.gif

    - assets/images/onBoardingScreen/ajan.png
    - assets/images/onBoardingScreen/bomba.png
    - assets/images/onBoardingScreen/discussions.png

    - assets/images/maps/Bind.png
    - assets/images/maps/Haven.png
    - assets/images/maps/Split.png
    - assets/images/maps/Ascent.png
    - assets/images/maps/Icebox.png
    - assets/images/maps/Breeze.png
    - assets/images/maps/Fracture.png
    - assets/images/maps/Pearl.png
    - assets/images/maps/Lotus.png
    - assets/images/maps/Sunset.png
    - assets/images/maps/Abyss.png

    - assets/images/agents/Brimstone.png
    - assets/images/agents/Viper.png
    - assets/images/agents/Omen.png
    - assets/images/agents/Killjoy.png
    - assets/images/agents/Cypher.png
    - assets/images/agents/Sova.png
    - assets/images/agents/Sage.png
    - assets/images/agents/Phoenix.png
    - assets/images/agents/Jett.png
    - assets/images/agents/Reyna.png
    - assets/images/agents/Raze.png
    - assets/images/agents/Breach.png
    - assets/images/agents/Skye.png
    - assets/images/agents/Yoru.png
    - assets/images/agents/Astra.png
    - assets/images/agents/KAYO.png
    - assets/images/agents/Chamber.png
    - assets/images/agents/Neon.png
    - assets/images/agents/Fade.png
    - assets/images/agents/Harbor.png
    - assets/images/agents/Gekko.png
    - assets/images/agents/Deadlock.png
    - assets/images/agents/Iso.png
    - assets/images/agents/Clove.png

  fonts:
    - family: valo-font
      fonts:
        - asset: assets/fonts/valo-font.ttf

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#131313"
  image: assets/splash/splash.png