name: valineups
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0-282.3.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  lottie: ^3.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: valo-font
      fonts:
        - asset: assets/fonts/valo-font.ttf

flutter_native_splash:
  color: "#1F1F1F"
  image: assets/images/splash.png
  android: true
  ios: true